dist: trusty
os: linux
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cmake
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - export CC=gcc-7
  - make -C ./tests/
  - make -C ./tests/main/
  - make -C ./tests/codecov/
after_success:
  - bash <(curl -s https://codecov.io/bash)
